### ISSUE TITLE
发布计划询问

### ISSUE THREAD

**Issue by lohaaa** [liuweichaox/SwaggerDoc#5]
作者您好

对之前的PR内容近期有发布计划吗?

[Pull Request](https://github.com/liuweichaox/SwaggerDoc/pull/4)

因为近期项目文档变更频繁,每次变更都需要手动调整部分格式解析失败的内容,所以自作主张上传了一个修复后版本到NuGet仓库自用,如您对此有任何意见,请回复我进行删除.

[NuGet](https://www.nuget.org/packages/LH.SwaggerDoc)

**Comment by liuweichaox** [comment]
感谢您的贡献，我将在今晚发布一版
